function [] = keyboard_gui()
set(0,'units','pix')
SCR = get(0,'screensize');
S.fh = figure('menubar','none',...
              'numbertitle','off',...
              'name','Friendly Keyboard',...
              'units','pix',...
              'resize','off',...
              'position',[20 20 SCR(3)-25 SCR(4)-80],...
              'color',[.5 .5 1]);
S.POS = cell(28,1);  % Pre-allocate so we get a column vector.
for ii = 1:26  % Create the letter buttons.
    ax = subplot(5,6,ii);  % Use SUBPLOT to get alignment.
    set(ax,'units','normalized','visible','off')
    S.POS{ii} = round(get(ax,'pos')*1000)/1000 - [0 .075 0 0];
    delete(ax)
    S.pb(ii) = uicontrol('style','push',...
                         'units','norm',...
                         'position',S.POS{ii},...
                         'string',char(64+ii),...
                         'fontsize',45,...
                         'fontweight','bold',...
                         'enable','off');
end
pwidth = S.POS{2}(3)+S.POS{2}(1)-S.POS{1}(1);
S.POS{27} = [S.POS{3}(1) S.POS{26}(2) pwidth S.POS{1}(4)]; % BACKSPACE button.
S.pb(27) =  uicontrol('style','push',...
                     'units','norm',...
                     'position',S.POS{27}+[0 0 .2705 0],...
                     'string','Delete',...
                     'fontsize',35,...
                     'fontweight','bold',...
                     'enable','off');  
S.pb(28) = uicontrol('style','push',...                 % The CLEAR button.
                     'units','norm',...
                     'position',[0.84625 0.875 .10375 0.11],...
                     'string','Clear',...
                     'fontsize',35,...
                     'fontweight','bold',...
                     'enable','off');                                 
S.ed = uicontrol('style','edit',...
                 'units','norm',...
                 'position',[0.05 0.875 0.7825 0.11],...
                 'fontsize',50,...
                 'fontweight','bold',...
                 'horizontalalignment','left',...
                 'enable','off'); 
set(S.pb,'backgroundcolor',[.9 .6 .6])             
drawnow       % Flush event queue